# Generated by Django 2.1 on 2018-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclista', models.CharField(max_length=100)),
                ('end_coleta', models.CharField(max_length=200)),
                ('end_entrega', models.CharField(max_length=200)),
                ('urgencia', models.IntegerField()),
            ],
        ),
    ]
