# Generated by Django 2.1 on 2018-09-15 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180903_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 15, 27, 14, 568708, tzinfo=utc)),
        ),
    ]
