# Generated by Django 2.1 on 2018-09-15 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_entrega_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='data',
        ),
        migrations.AddField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 15, 31, 12, 209191, tzinfo=utc)),
        ),
    ]
