# Generated by Django 2.0.8 on 2018-09-15 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180915_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 15, 36, 52, 872542, tzinfo=utc)),
        ),
    ]
