# Generated by Django 2.1 on 2018-09-15 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180915_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='entrega',
            name='ciclista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ciclista'),
        ),
        migrations.AlterField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 15, 46, 5, 624088, tzinfo=utc)),
        ),
    ]
