# Generated by Django 2.1 on 2018-09-15 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180915_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='ciclista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ciclista'),
        ),
        migrations.AlterField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 16, 1, 26, 137228, tzinfo=utc)),
        ),
    ]
