# Generated by Django 2.1 on 2018-09-15 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180915_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 16, 11, 47, 419980, tzinfo=utc)),
        ),
    ]
