# Generated by Django 2.1 on 2018-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180916_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel'), ('E', 'Em andamento')], default='D', max_length=2, null=True),
        ),
    ]
