# Generated by Django 2.1 on 2018-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180916_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclista',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel'), ('E', 'Em entrega'), ('O', 'Offline')], default='D', max_length=2, null=True),
        ),
    ]
