# Generated by Django 2.1 on 2018-09-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180915_1236'),
        ('home', '0013_auto_20180916_0047'),
    ]

    operations = [
    ]
