# Generated by Django 2.1 on 2018-10-02 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20180916_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
