# Generated by Django 2.1 on 2018-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181002_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeolocation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usergeolocation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
