# Generated by Django 2.1 on 2018-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20181008_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaativa',
            name='data_coleta',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='entregaativa',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
