# Generated by Django 2.1 on 2018-10-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20181011_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaativa',
            name='data_coleta',
        ),
        migrations.RemoveField(
            model_name='entregaativa',
            name='data_entrega',
        ),
    ]
