# Generated by Django 2.1 on 2018-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20181011_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaativa',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
