# Generated by Django 2.1 on 2018-10-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20181011_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='data_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaativa',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
