# Generated by Django 2.1 on 2018-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20181011_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
