# Generated by Django 2.1 on 2018-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20181011_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='data',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
