# Generated by Django 2.1 on 2018-10-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_entrega_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaativa',
            name='tempo_estimado',
            field=models.FloatField(null=True),
        ),
    ]
