# Generated by Django 2.1 on 2018-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_entregaativa_tempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaativa',
            name='distancia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entregaativa',
            name='tempo_estimado',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
